### PR TITLE
Convert imports to relative imports

### PR DESCRIPTION
**Pull request by NWylynko**
To import the LoadExcelInputs file in to our codebase the imports in the file need to be relative otherwise python gets confused. Please test to ensure these changes don't break anything, if they do we will need to find another solution.

### CODE REVIEW

**Comment by youngmr290** [comment]
The changes give me this error: ImportError: attempted relative import beyond top-level package
But I am wondering why you needed to change the importing in the four files you changed because those files are only used for the raw version and shouldn't be required for the web app?

**Comment by youngmr290** [comment]
Still not working on my end.

**Comment by NWylynko** [comment]
So here i have moved the two modules into a folder called lib (short for library), then updated all the imports to start with "lib." From my initial testing this seems to let your imports work as python knows to look in the lib folder and on our side we can do "app.module.afo.lib.*" to get to the files we need. Please test this to see if it works, also any reading of files might need to be updated if they are imported relative to the location of the python file reading them. If they are relative to the RunAfoRaw python file then they shouldn't need changing.

**Comment by youngmr290** [comment]
okay that works. I'll merge to master in a tick

**Comment by NWylynko** [comment]
beautiful, thanks

**Comment by youngmr290** [comment]
Yeh there are just some error where it is looking for files in the code e.g. line 96 of loadexp.py.

**Comment by NWylynko** [comment]
yeah, Things like that I think just have to tell them to look inside lib/AfoLogic/*, do you want me to attempt to fix them?

**Comment by youngmr290** [comment]
Yeh that works. I can't find any other issues other than that one. All the other files that i look at in the raw version are excel files and pkl files and they didnt change location.
So if you can just push that one change then we should be good to go

**Comment by NWylynko** [comment]
If there are any other changes you need me to make just let me know

**Pull request merged**
